# Parallelization parameters
max_workers_pima=1 # Number of PDBs to process in parallel
max_workers_ppcheck=4 # Number of chain combinations for each PDB to process in parallel
max_number_of_chains=20 # Maximum number of chains to process. If more than this number, the PDB will be skipped
max_ram_mb=None # in MB

# Flags to run the different tools
RUN_PPCHECK=True
RUN_HOTPIES=True
RUN_SASA=False
RUN_INTERFACE_ASYMMETRY=False
CLEANUP=False # Will delete all the temporary files created by the tools. Remember to set to False if you want to run HotPIES later
OVERWRITE=True

# Directories
PIMA_scripts_dir=/home/aditi/HDD_Home/PIMADB_Update_Nov2024/PIMA
hotpies_codes_folder=/home/aditi/HDD_Home/PIMADB_Update_Nov2024/PIMA/hotpies_codes# Folder with the hotpies codes
output_folder=/home/aditi/HDD_Home/PIMADB_Update_Nov2024/ppcheck_results # Output directory
ppcheck_codes_folder=/home/aditi/HDD_Home/PIMADB_Update_Nov2024/PIMA/ppcheck_codes # Folder with the ppcheck codes
freesasa_path=/home/aditi/HDD_Home/PIMADB_Update_Nov2024/PIMA/freesasa/src/freesasa # Path to the freesasa executable

# PDB List properties
pdb_number_start=0 # Start PDB number 
pdb_number_end=None # End PDB number 
batch_number=None


structure_file_format={}.cif # Structure file format
size_sort=True # Sort PDBs by size (smallest to largest)